version: '3.3'
services:
    app-pgsql-crud:
        image: postgres:9.5-alpine
        container_name: app-pgsql-crud
        restart: always
        expose:
            - 5454
        ports:
            - 5454:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: araujo123
            POSTGRES_DB: crud_deportes
            POSTGRES_HOST_AUTH_METHOD: md5
